language: python
dist: trusty
branches:
  only:
  - conda

python:
  - 2.7

install:
  - apt-get update -qq
  - apt-get upgrade -qq
  - apt-get install -qq build-essential
  - apt-get install -qq libboost-all-dev
  - apt-get install -qq ccache
  - apt-get install -qq libgsl0-dev

  - mkdir -p ~/.config/matplotlib
  - mkdir -p ~/.matplotlib
  - echo 'backend: agg' > ~/.config/matplotlib/matplotlibrc
  - echo 'backend: agg' > ~/.matplotlib/matplotlibrc
  - echo 'backend: agg' > ~/.matplotlibrc

  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build

script:
  - export CONDA_PACKAGE_VERSION="$(git describe --exact match 2> /dev/null || git describe | sed 's/^v\([^-]*\).*/\1_dev/')"
  - conda build . -c probcomp
  - conda install crosscat --use-local -c probcomp

after_success:
  - conda install anaconda-client
  - anaconda -t $CONDA_UPLOAD_TOKEN upload -u $CONDA_USER ~/miniconda/conda-bld/linux-64/venture-*.tar.bz2 --force
