package:
  name: venture
  version: "0.1"

source:
  path: ../

build:
  script: python setup.py install

requirements:
  build:
    - git
    - anaconda # probably don't need this
    - python 2.7.*
  run:
    - python 2.7.*
    - numpy >=1.8
    - scipy >=0.13
    - matplotlib >=1.3.1
    - patsy >=0.2
    - pandas >=0.14,<0.19
    - networkx
    - flask >=0.10
    - requests >=1.2
    - jsonschema

test:
  requires:
    - python 2.7.*
    - nose
    # - nose-testconfig
    - pexpect
  # commands:
  #   - python -m pytest --pyargs crosscat

about:
  home: https://github.com/probcomp/Venturecxx
  license: Apache
  license_file: LICENSE
