package:
  name: venture
  version: {{ CONDA_PACKAGE_VERSION }}

source:
  path: ../

build:
  script: python setup.py install

source:
  path: ../

requirements:
  build:
    - git
    - python 3.6.*
  run:
    - flask >=0.10
    - jsonschema
    - matplotlib 2.1.*
    - networkx
    - numpy 1.13.*
    - pandas 0.23.*
    - patsy >=0.2
    - python 3.6.*
    - requests >=1.2
    - scipy 1.0.*
    - six 1.11.*

test:
  source_files:
    - test
    - examples
  requires:
    - markdown2 # For building the tutorial with venture-transcript. TODO Is markdown2 a real dependency?
    - matplotlib 2.1.*
    - nose >=1.3
    - pexpect
    - pytest 3.6.*
    - python 3.6.*
    - six 1.11.*
  commands:
    - nosetests -c lite-crashes.cfg -w test -e integration

about:
  home: https://github.com/probcomp/Venturecxx
  license: Apache
  license_file: LICENSE
