package:
  name: venture
  version: {{ CONDA_PACKAGE_VERSION }}

source:
  path: ../

build:
  script: python setup.py install

source:
  path: ../

requirements:
  build:
    - git
    - python 2.7.*
  run:
    - python 2.7.*
    - numpy >=1.8
    - matplotlib >=1.3.1,<2.0
    - networkx
    - patsy >=0.2
    - pandas >=0.14,<0.19
    - flask >=0.10
    - requests >=1.2
    - scipy >=0.13,<=0.19
    - six 1.10.*
    - jsonschema

test:
  source_files:
    - test
    - examples
  requires:
    - python 2.7.*
    - matplotlib >=1.3.1,<2.0
    - nose
    - pexpect
    - scipy >=0.13,<=0.19
    - six 1.10.*
  commands:
    - nosetests -c lite-crashes.cfg -w test -e integration

about:
  home: https://github.com/probcomp/Venturecxx
  license: Apache
  license_file: LICENSE
